# Generated by Django 4.1.4 on 2023-01-31 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("generateCard", "0003_cardgenerated_card_expiry_year_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="initialpayment",
            name="coinpayment_tx_hash",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="initialpayment",
            name="payed_from_wallet_address",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="initialpayment",
            name="payed_transaction_hash",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="initialpayment",
            name="timestamp_finished",
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name="topupcard",
            name="coinpayment_tx_hash",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="topupcard",
            name="payed_from_wallet_address",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="topupcard",
            name="payed_transaction_hash",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="topupcard",
            name="timestamp_finished",
            field=models.DateTimeField(null=True),
        ),
    ]
