# Generated by Django 4.1.4 on 2023-01-31 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("generateCard", "0004_alter_initialpayment_coinpayment_tx_hash_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="initialpayment",
            name="coinpayment_tx_hash",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="initialpayment",
            name="payed_from_wallet_address",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="initialpayment",
            name="payed_transaction_hash",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="initialpayment",
            name="timestamp_finished",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="topupcard",
            name="coinpayment_tx_hash",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="topupcard",
            name="payed_from_wallet_address",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="topupcard",
            name="payed_transaction_hash",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="topupcard",
            name="timestamp_finished",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
