# Generated by Django 4.1.4 on 2023-01-31 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("generateCard", "0005_alter_initialpayment_coinpayment_tx_hash_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="cardgenerated",
            name="card_balance",
            field=models.IntegerField(default=51),
            preserve_default=False,
        ),
    ]
