# Generated by Django 4.1.4 on 2023-02-01 15:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("generateCard", "0006_cardgenerated_card_balance"),
    ]

    operations = [
        migrations.AddField(
            model_name="initialpayment",
            name="card_holder_addressline1",
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="initialpayment",
            name="card_holder_addressline2",
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="initialpayment",
            name="card_holder_city",
            field=models.CharField(default=1, max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="initialpayment",
            name="card_holder_country",
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="initialpayment",
            name="card_holder_name",
            field=models.CharField(default=1, max_length=40),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="initialpayment",
            name="card_holder_surname",
            field=models.CharField(default=1, max_length=40),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="initialpayment",
            name="card_holder_zip",
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="initialpayment",
            name="card_type",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="generateCard.cardtypes",
            ),
            preserve_default=False,
        ),
    ]
