# Generated by Django 4.1.4 on 2023-02-04 09:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("generateCard", "0008_cardgenerated_card_holder_state_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="userwallet",
            old_name="wallet_user",
            new_name="user",
        ),
        migrations.RenameField(
            model_name="userwallet",
            old_name="user_wallet",
            new_name="wallet",
        ),
    ]
