# Generated by Django 4.1.4 on 2023-02-07 10:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("generateCard", "0012_alter_userwallet_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userwallet",
            name="user",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
