# Generated by Django 4.1.4 on 2023-02-20 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("generateCard", "0015_twofaauth"),
    ]

    operations = [
        migrations.AddField(
            model_name="twofaauth",
            name="block",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="twofaauth",
            name="block_time_over",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
