country = [
    {
        "name": "Algeria",
        "alpha-2": "DZ",
        "alpha-3": "DZA",
        "country-code": "012",
        "iso_3166-2": "ISO 3166-2:DZ",
        "region": "Africa",
        "sub-region": "Northern Africa",
        "intermediate-region": "",
        "region-code": "002",
        "sub-region-code": "015",
        "intermediate-region-code": ""
    },
    {
        "name": "Angola",
        "alpha-2": "AO",
        "alpha-3": "AGO",
        "country-code": "024",
        "iso_3166-2": "ISO 3166-2:AO",
        "region": "Africa",
        "sub-region": "Sub-Saharan Africa",
        "intermediate-region": "Middle Africa",
        "region-code": "002",
        "sub-region-code": "202",
        "intermediate-region-code": "017"
    },
    {
        "name": "Argentina",
        "alpha-2": "AR",
        "alpha-3": "ARG",
        "country-code": "032",
        "iso_3166-2": "ISO 3166-2:AR",
        "region": "Americas",
        "sub-region": "Latin America and the Caribbean",
        "intermediate-region": "South America",
        "region-code": "019",
        "sub-region-code": "419",
        "intermediate-region-code": "005"
    },
    {
        "name": "Australia",
        "alpha-2": "AU",
        "alpha-3": "AUS",
        "country-code": "036",
        "iso_3166-2": "ISO 3166-2:AU",
        "region": "Oceania",
        "sub-region": "Australia and New Zealand",
        "intermediate-region": "",
        "region-code": "009",
        "sub-region-code": "053",
        "intermediate-region-code": ""
    },
    {
        "name": "Austria",
        "alpha-2": "AT",
        "alpha-3": "AUT",
        "country-code": "040",
        "iso_3166-2": "ISO 3166-2:AT",
        "region": "Europe",
        "sub-region": "Western Europe",
        "intermediate-region": "",
        "region-code": "150",
        "sub-region-code": "155",
        "intermediate-region-code": ""
    },
    {
        "name": "Bahamas",
        "alpha-2": "BS",
        "alpha-3": "BHS",
        "country-code": "044",
        "iso_3166-2": "ISO 3166-2:BS",
        "region": "Americas",
        "sub-region": "Latin America and the Caribbean",
        "intermediate-region": "Caribbean",
        "region-code": "019",
        "sub-region-code": "419",
        "intermediate-region-code": "029"
    },
    {
        "name": "Barbados",
        "alpha-2": "BB",
        "alpha-3": "BRB",
        "country-code": "052",
        "iso_3166-2": "ISO 3166-2:BB",
        "region": "Americas",
        "sub-region": "Latin America and the Caribbean",
        "intermediate-region": "Caribbean",
        "region-code": "019",
        "sub-region-code": "419",
        "intermediate-region-code": "029"
    },
    {
        "name": "Belgium",
        "alpha-2": "BE",
        "alpha-3": "BEL",
        "country-code": "056",
        "iso_3166-2": "ISO 3166-2:BE",
        "region": "Europe",
        "sub-region": "Western Europe",
        "intermediate-region": "",
        "region-code": "150",
        "sub-region-code": "155",
        "intermediate-region-code": ""
    },
    {
        "name": "Benin",
        "alpha-2": "BJ",
        "alpha-3": "BEN",
        "country-code": "204",
        "iso_3166-2": "ISO 3166-2:BJ",
        "region": "Africa",
        "sub-region": "Sub-Saharan Africa",
        "intermediate-region": "Western Africa",
        "region-code": "002",
        "sub-region-code": "202",
        "intermediate-region-code": "011"
    },
    {
        "name": "Bolivia (Plurinational State of)",
        "alpha-2": "BO",
        "alpha-3": "BOL",
        "country-code": "068",
        "iso_3166-2": "ISO 3166-2:BO",
        "region": "Americas",
        "sub-region": "Latin America and the Caribbean",
        "intermediate-region": "South America",
        "region-code": "019",
        "sub-region-code": "419",
        "intermediate-region-code": "005"
    },
    {
        "name": "Brazil",
        "alpha-2": "BR",
        "alpha-3": "BRA",
        "country-code": "076",
        "iso_3166-2": "ISO 3166-2:BR",
        "region": "Americas",
        "sub-region": "Latin America and the Caribbean",
        "intermediate-region": "South America",
        "region-code": "019",
        "sub-region-code": "419",
        "intermediate-region-code": "005"
    },
    {
        "name": "Burkina Faso",
        "alpha-2": "BF",
        "alpha-3": "BFA",
        "country-code": "854",
        "iso_3166-2": "ISO 3166-2:BF",
        "region": "Africa",
        "sub-region": "Sub-Saharan Africa",
        "intermediate-region": "Western Africa",
        "region-code": "002",
        "sub-region-code": "202",
        "intermediate-region-code": "011"
    },
    {
        "name": "Cambodia",
        "alpha-2": "KH",
        "alpha-3": "KHM",
        "country-code": "116",
        "iso_3166-2": "ISO 3166-2:KH",
        "region": "Asia",
        "sub-region": "South-eastern Asia",
        "intermediate-region": "",
        "region-code": "142",
        "sub-region-code": "035",
        "intermediate-region-code": ""
    },
    {
        "name": "Cameroon",
        "alpha-2": "CM",
        "alpha-3": "CMR",
        "country-code": "120",
        "iso_3166-2": "ISO 3166-2:CM",
        "region": "Africa",
        "sub-region": "Sub-Saharan Africa",
        "intermediate-region": "Middle Africa",
        "region-code": "002",
        "sub-region-code": "202",
        "intermediate-region-code": "017"
    },
    {
        "name": "Canada",
        "alpha-2": "CA",
        "alpha-3": "CAN",
        "country-code": "124",
        "iso_3166-2": "ISO 3166-2:CA",
        "region": "Americas",
        "sub-region": "Northern America",
        "intermediate-region": "",
        "region-code": "019",
        "sub-region-code": "021",
        "intermediate-region-code": ""
    },
    {
        "name": "Cayman Islands",
        "alpha-2": "KY",
        "alpha-3": "CYM",
        "country-code": "136",
        "iso_3166-2": "ISO 3166-2:KY",
        "region": "Americas",
        "sub-region": "Latin America and the Caribbean",
        "intermediate-region": "Caribbean",
        "region-code": "019",
        "sub-region-code": "419",
        "intermediate-region-code": "029"
    },
    {
        "name": "Chad",
        "alpha-2": "TD",
        "alpha-3": "TCD",
        "country-code": "148",
        "iso_3166-2": "ISO 3166-2:TD",
        "region": "Africa",
        "sub-region": "Sub-Saharan Africa",
        "intermediate-region": "Middle Africa",
        "region-code": "002",
        "sub-region-code": "202",
        "intermediate-region-code": "017"
    },
    {
        "name": "Chile",
        "alpha-2": "CL",
        "alpha-3": "CHL",
        "country-code": "152",
        "iso_3166-2": "ISO 3166-2:CL",
        "region": "Americas",
        "sub-region": "Latin America and the Caribbean",
        "intermediate-region": "South America",
        "region-code": "019",
        "sub-region-code": "419",
        "intermediate-region-code": "005"
    },
    {
        "name": "Colombia",
        "alpha-2": "CO",
        "alpha-3": "COL",
        "country-code": "170",
        "iso_3166-2": "ISO 3166-2:CO",
        "region": "Americas",
        "sub-region": "Latin America and the Caribbean",
        "intermediate-region": "South America",
        "region-code": "019",
        "sub-region-code": "419",
        "intermediate-region-code": "005"
    },
    {
        "name": "Comoros",
        "alpha-2": "KM",
        "alpha-3": "COM",
        "country-code": "174",
        "iso_3166-2": "ISO 3166-2:KM",
        "region": "Africa",
        "sub-region": "Sub-Saharan Africa",
        "intermediate-region": "Eastern Africa",
        "region-code": "002",
        "sub-region-code": "202",
        "intermediate-region-code": "014"
    },
    {
        "name": "Congo",
        "alpha-2": "CG",
        "alpha-3": "COG",
        "country-code": "178",
        "iso_3166-2": "ISO 3166-2:CG",
        "region": "Africa",
        "sub-region": "Sub-Saharan Africa",
        "intermediate-region": "Middle Africa",
        "region-code": "002",
        "sub-region-code": "202",
        "intermediate-region-code": "017"
    },
    {
        "name": "Congo, Democratic Republic of the",
        "alpha-2": "CD",
        "alpha-3": "COD",
        "country-code": "180",
        "iso_3166-2": "ISO 3166-2:CD",
        "region": "Africa",
        "sub-region": "Sub-Saharan Africa",
        "intermediate-region": "Middle Africa",
        "region-code": "002",
        "sub-region-code": "202",
        "intermediate-region-code": "017"
    },
    {
        "name": "Costa Rica",
        "alpha-2": "CR",
        "alpha-3": "CRI",
        "country-code": "188",
        "iso_3166-2": "ISO 3166-2:CR",
        "region": "Americas",
        "sub-region": "Latin America and the Caribbean",
        "intermediate-region": "Central America",
        "region-code": "019",
        "sub-region-code": "419",
        "intermediate-region-code": "013"
    },
    {
        "name": "Cyprus",
        "alpha-2": "CY",
        "alpha-3": "CYP",
        "country-code": "196",
        "iso_3166-2": "ISO 3166-2:CY",
        "region": "Asia",
        "sub-region": "Western Asia",
        "intermediate-region": "",
        "region-code": "142",
        "sub-region-code": "145",
        "intermediate-region-code": ""
    },
    {
        "name": "Czechia",
        "alpha-2": "CZ",
        "alpha-3": "CZE",
        "country-code": "203",
        "iso_3166-2": "ISO 3166-2:CZ",
        "region": "Europe",
        "sub-region": "Eastern Europe",
        "intermediate-region": "",
        "region-code": "150",
        "sub-region-code": "151",
        "intermediate-region-code": ""
    },
    {
        "name": "Denmark",
        "alpha-2": "DK",
        "alpha-3": "DNK",
        "country-code": "208",
        "iso_3166-2": "ISO 3166-2:DK",
        "region": "Europe",
        "sub-region": "Northern Europe",
        "intermediate-region": "",
        "region-code": "150",
        "sub-region-code": "154",
        "intermediate-region-code": ""
    },
    {
        "name": "Dominica",
        "alpha-2": "DM",
        "alpha-3": "DMA",
        "country-code": "212",
        "iso_3166-2": "ISO 3166-2:DM",
        "region": "Americas",
        "sub-region": "Latin America and the Caribbean",
        "intermediate-region": "Caribbean",
        "region-code": "019",
        "sub-region-code": "419",
        "intermediate-region-code": "029"
    },
    {
        "name": "Dominican Republic",
        "alpha-2": "DO",
        "alpha-3": "DOM",
        "country-code": "214",
        "iso_3166-2": "ISO 3166-2:DO",
        "region": "Americas",
        "sub-region": "Latin America and the Caribbean",
        "intermediate-region": "Caribbean",
        "region-code": "019",
        "sub-region-code": "419",
        "intermediate-region-code": "029"
    },
    {
        "name": "Ecuador",
        "alpha-2": "EC",
        "alpha-3": "ECU",
        "country-code": "218",
        "iso_3166-2": "ISO 3166-2:EC",
        "region": "Americas",
        "sub-region": "Latin America and the Caribbean",
        "intermediate-region": "South America",
        "region-code": "019",
        "sub-region-code": "419",
        "intermediate-region-code": "005"
    },
    {
        "name": "Egypt",
        "alpha-2": "EG",
        "alpha-3": "EGY",
        "country-code": "818",
        "iso_3166-2": "ISO 3166-2:EG",
        "region": "Africa",
        "sub-region": "Northern Africa",
        "intermediate-region": "",
        "region-code": "002",
        "sub-region-code": "015",
        "intermediate-region-code": ""
    },
    {
        "name": "El Salvador",
        "alpha-2": "SV",
        "alpha-3": "SLV",
        "country-code": "222",
        "iso_3166-2": "ISO 3166-2:SV",
        "region": "Americas",
        "sub-region": "Latin America and the Caribbean",
        "intermediate-region": "Central America",
        "region-code": "019",
        "sub-region-code": "419",
        "intermediate-region-code": "013"
    },
    {
        "name": "Eritrea",
        "alpha-2": "ER",
        "alpha-3": "ERI",
        "country-code": "232",
        "iso_3166-2": "ISO 3166-2:ER",
        "region": "Africa",
        "sub-region": "Sub-Saharan Africa",
        "intermediate-region": "Eastern Africa",
        "region-code": "002",
        "sub-region-code": "202",
        "intermediate-region-code": "014"
    },
    {
        "name": "Estonia",
        "alpha-2": "EE",
        "alpha-3": "EST",
        "country-code": "233",
        "iso_3166-2": "ISO 3166-2:EE",
        "region": "Europe",
        "sub-region": "Northern Europe",
        "intermediate-region": "",
        "region-code": "150",
        "sub-region-code": "154",
        "intermediate-region-code": ""
    },
    {
        "name": "Finland",
        "alpha-2": "FI",
        "alpha-3": "FIN",
        "country-code": "246",
        "iso_3166-2": "ISO 3166-2:FI",
        "region": "Europe",
        "sub-region": "Northern Europe",
        "intermediate-region": "",
        "region-code": "150",
        "sub-region-code": "154",
        "intermediate-region-code": ""
    },
    {
        "name": "France",
        "alpha-2": "FR",
        "alpha-3": "FRA",
        "country-code": "250",
        "iso_3166-2": "ISO 3166-2:FR",
        "region": "Europe",
        "sub-region": "Western Europe",
        "intermediate-region": "",
        "region-code": "150",
        "sub-region-code": "155",
        "intermediate-region-code": ""
    },
    {
        "name": "Georgia",
        "alpha-2": "GE",
        "alpha-3": "GEO",
        "country-code": "268",
        "iso_3166-2": "ISO 3166-2:GE",
        "region": "Asia",
        "sub-region": "Western Asia",
        "intermediate-region": "",
        "region-code": "142",
        "sub-region-code": "145",
        "intermediate-region-code": ""
    },
    {
        "name": "Germany",
        "alpha-2": "DE",
        "alpha-3": "DEU",
        "country-code": "276",
        "iso_3166-2": "ISO 3166-2:DE",
        "region": "Europe",
        "sub-region": "Western Europe",
        "intermediate-region": "",
        "region-code": "150",
        "sub-region-code": "155",
        "intermediate-region-code": ""
    },
    {
        "name": "Ghana",
        "alpha-2": "GH",
        "alpha-3": "GHA",
        "country-code": "288",
        "iso_3166-2": "ISO 3166-2:GH",
        "region": "Africa",
        "sub-region": "Sub-Saharan Africa",
        "intermediate-region": "Western Africa",
        "region-code": "002",
        "sub-region-code": "202",
        "intermediate-region-code": "011"
    },
    {
        "name": "Greece",
        "alpha-2": "GR",
        "alpha-3": "GRC",
        "country-code": "300",
        "iso_3166-2": "ISO 3166-2:GR",
        "region": "Europe",
        "sub-region": "Southern Europe",
        "intermediate-region": "",
        "region-code": "150",
        "sub-region-code": "039",
        "intermediate-region-code": ""
    },
    {
        "name": "Guatemala",
        "alpha-2": "GT",
        "alpha-3": "GTM",
        "country-code": "320",
        "iso_3166-2": "ISO 3166-2:GT",
        "region": "Americas",
        "sub-region": "Latin America and the Caribbean",
        "intermediate-region": "Central America",
        "region-code": "019",
        "sub-region-code": "419",
        "intermediate-region-code": "013"
    },
    {
        "name": "Guinea",
        "alpha-2": "GN",
        "alpha-3": "GIN",
        "country-code": "324",
        "iso_3166-2": "ISO 3166-2:GN",
        "region": "Africa",
        "sub-region": "Sub-Saharan Africa",
        "intermediate-region": "Western Africa",
        "region-code": "002",
        "sub-region-code": "202",
        "intermediate-region-code": "011"
    },
    {
        "name": "Guinea-Bissau",
        "alpha-2": "GW",
        "alpha-3": "GNB",
        "country-code": "624",
        "iso_3166-2": "ISO 3166-2:GW",
        "region": "Africa",
        "sub-region": "Sub-Saharan Africa",
        "intermediate-region": "Western Africa",
        "region-code": "002",
        "sub-region-code": "202",
        "intermediate-region-code": "011"
    },
    {
        "name": "Haiti",
        "alpha-2": "HT",
        "alpha-3": "HTI",
        "country-code": "332",
        "iso_3166-2": "ISO 3166-2:HT",
        "region": "Americas",
        "sub-region": "Latin America and the Caribbean",
        "intermediate-region": "Caribbean",
        "region-code": "019",
        "sub-region-code": "419",
        "intermediate-region-code": "029"
    },
    {
        "name": "Honduras",
        "alpha-2": "HN",
        "alpha-3": "HND",
        "country-code": "340",
        "iso_3166-2": "ISO 3166-2:HN",
        "region": "Americas",
        "sub-region": "Latin America and the Caribbean",
        "intermediate-region": "Central America",
        "region-code": "019",
        "sub-region-code": "419",
        "intermediate-region-code": "013"
    },
    {
        "name": "Hungary",
        "alpha-2": "HU",
        "alpha-3": "HUN",
        "country-code": "348",
        "iso_3166-2": "ISO 3166-2:HU",
        "region": "Europe",
        "sub-region": "Eastern Europe",
        "intermediate-region": "",
        "region-code": "150",
        "sub-region-code": "151",
        "intermediate-region-code": ""
    },
    {
        "name": "Iceland",
        "alpha-2": "IS",
        "alpha-3": "ISL",
        "country-code": "352",
        "iso_3166-2": "ISO 3166-2:IS",
        "region": "Europe",
        "sub-region": "Northern Europe",
        "intermediate-region": "",
        "region-code": "150",
        "sub-region-code": "154",
        "intermediate-region-code": ""
    },
    {
        "name": "Ireland",
        "alpha-2": "IE",
        "alpha-3": "IRL",
        "country-code": "372",
        "iso_3166-2": "ISO 3166-2:IE",
        "region": "Europe",
        "sub-region": "Northern Europe",
        "intermediate-region": "",
        "region-code": "150",
        "sub-region-code": "154",
        "intermediate-region-code": ""
    },
    {
        "name": "Italy",
        "alpha-2": "IT",
        "alpha-3": "ITA",
        "country-code": "380",
        "iso_3166-2": "ISO 3166-2:IT",
        "region": "Europe",
        "sub-region": "Southern Europe",
        "intermediate-region": "",
        "region-code": "150",
        "sub-region-code": "039",
        "intermediate-region-code": ""
    },
    {
        "name": "Jamaica",
        "alpha-2": "JM",
        "alpha-3": "JAM",
        "country-code": "388",
        "iso_3166-2": "ISO 3166-2:JM",
        "region": "Americas",
        "sub-region": "Latin America and the Caribbean",
        "intermediate-region": "Caribbean",
        "region-code": "019",
        "sub-region-code": "419",
        "intermediate-region-code": "029"
    },
    {
        "name": "Japan",
        "alpha-2": "JP",
        "alpha-3": "JPN",
        "country-code": "392",
        "iso_3166-2": "ISO 3166-2:JP",
        "region": "Asia",
        "sub-region": "Eastern Asia",
        "intermediate-region": "",
        "region-code": "142",
        "sub-region-code": "030",
        "intermediate-region-code": ""
    },
    {
        "name": "Jordan",
        "alpha-2": "JO",
        "alpha-3": "JOR",
        "country-code": "400",
        "iso_3166-2": "ISO 3166-2:JO",
        "region": "Asia",
        "sub-region": "Western Asia",
        "intermediate-region": "",
        "region-code": "142",
        "sub-region-code": "145",
        "intermediate-region-code": ""
    },
    {
        "name": "Kenya",
        "alpha-2": "KE",
        "alpha-3": "KEN",
        "country-code": "404",
        "iso_3166-2": "ISO 3166-2:KE",
        "region": "Africa",
        "sub-region": "Sub-Saharan Africa",
        "intermediate-region": "Eastern Africa",
        "region-code": "002",
        "sub-region-code": "202",
        "intermediate-region-code": "014"
    },
    {
        "name": "Korea (Democratic People's Republic of)",
        "alpha-2": "KP",
        "alpha-3": "PRK",
        "country-code": "408",
        "iso_3166-2": "ISO 3166-2:KP",
        "region": "Asia",
        "sub-region": "Eastern Asia",
        "intermediate-region": "",
        "region-code": "142",
        "sub-region-code": "030",
        "intermediate-region-code": ""
    },
    {
        "name": "Kuwait",
        "alpha-2": "KW",
        "alpha-3": "KWT",
        "country-code": "414",
        "iso_3166-2": "ISO 3166-2:KW",
        "region": "Asia",
        "sub-region": "Western Asia",
        "intermediate-region": "",
        "region-code": "142",
        "sub-region-code": "145",
        "intermediate-region-code": ""
    },
    {
        "name": "Lesotho",
        "alpha-2": "LS",
        "alpha-3": "LSO",
        "country-code": "426",
        "iso_3166-2": "ISO 3166-2:LS",
        "region": "Africa",
        "sub-region": "Sub-Saharan Africa",
        "intermediate-region": "Southern Africa",
        "region-code": "002",
        "sub-region-code": "202",
        "intermediate-region-code": "018"
    },
    {
        "name": "Liberia",
        "alpha-2": "LR",
        "alpha-3": "LBR",
        "country-code": "430",
        "iso_3166-2": "ISO 3166-2:LR",
        "region": "Africa",
        "sub-region": "Sub-Saharan Africa",
        "intermediate-region": "Western Africa",
        "region-code": "002",
        "sub-region-code": "202",
        "intermediate-region-code": "011"
    },
    {
        "name": "Lithuania",
        "alpha-2": "LT",
        "alpha-3": "LTU",
        "country-code": "440",
        "iso_3166-2": "ISO 3166-2:LT",
        "region": "Europe",
        "sub-region": "Northern Europe",
        "intermediate-region": "",
        "region-code": "150",
        "sub-region-code": "154",
        "intermediate-region-code": ""
    },
    {
        "name": "Luxembourg",
        "alpha-2": "LU",
        "alpha-3": "LUX",
        "country-code": "442",
        "iso_3166-2": "ISO 3166-2:LU",
        "region": "Europe",
        "sub-region": "Western Europe",
        "intermediate-region": "",
        "region-code": "150",
        "sub-region-code": "155",
        "intermediate-region-code": ""
    },
    {
        "name": "Madagascar",
        "alpha-2": "MG",
        "alpha-3": "MDG",
        "country-code": "450",
        "iso_3166-2": "ISO 3166-2:MG",
        "region": "Africa",
        "sub-region": "Sub-Saharan Africa",
        "intermediate-region": "Eastern Africa",
        "region-code": "002",
        "sub-region-code": "202",
        "intermediate-region-code": "014"
    },
    {
        "name": "Malawi",
        "alpha-2": "MW",
        "alpha-3": "MWI",
        "country-code": "454",
        "iso_3166-2": "ISO 3166-2:MW",
        "region": "Africa",
        "sub-region": "Sub-Saharan Africa",
        "intermediate-region": "Eastern Africa",
        "region-code": "002",
        "sub-region-code": "202",
        "intermediate-region-code": "014"
    },
    {
        "name": "Malaysia",
        "alpha-2": "MY",
        "alpha-3": "MYS",
        "country-code": "458",
        "iso_3166-2": "ISO 3166-2:MY",
        "region": "Asia",
        "sub-region": "South-eastern Asia",
        "intermediate-region": "",
        "region-code": "142",
        "sub-region-code": "035",
        "intermediate-region-code": ""
    },
    {
        "name": "Malta",
        "alpha-2": "MT",
        "alpha-3": "MLT",
        "country-code": "470",
        "iso_3166-2": "ISO 3166-2:MT",
        "region": "Europe",
        "sub-region": "Southern Europe",
        "intermediate-region": "",
        "region-code": "150",
        "sub-region-code": "039",
        "intermediate-region-code": ""
    },
    {
        "name": "Mexico",
        "alpha-2": "MX",
        "alpha-3": "MEX",
        "country-code": "484",
        "iso_3166-2": "ISO 3166-2:MX",
        "region": "Americas",
        "sub-region": "Latin America and the Caribbean",
        "intermediate-region": "Central America",
        "region-code": "019",
        "sub-region-code": "419",
        "intermediate-region-code": "013"
    },
    {
        "name": "Morocco",
        "alpha-2": "MA",
        "alpha-3": "MAR",
        "country-code": "504",
        "iso_3166-2": "ISO 3166-2:MA",
        "region": "Africa",
        "sub-region": "Northern Africa",
        "intermediate-region": "",
        "region-code": "002",
        "sub-region-code": "015",
        "intermediate-region-code": ""
    },
    {
        "name": "Mozambique",
        "alpha-2": "MZ",
        "alpha-3": "MOZ",
        "country-code": "508",
        "iso_3166-2": "ISO 3166-2:MZ",
        "region": "Africa",
        "sub-region": "Sub-Saharan Africa",
        "intermediate-region": "Eastern Africa",
        "region-code": "002",
        "sub-region-code": "202",
        "intermediate-region-code": "014"
    },
    {
        "name": "Myanmar",
        "alpha-2": "MM",
        "alpha-3": "MMR",
        "country-code": "104",
        "iso_3166-2": "ISO 3166-2:MM",
        "region": "Asia",
        "sub-region": "South-eastern Asia",
        "intermediate-region": "",
        "region-code": "142",
        "sub-region-code": "035",
        "intermediate-region-code": ""
    },
    {
        "name": "Nepal",
        "alpha-2": "NP",
        "alpha-3": "NPL",
        "country-code": "524",
        "iso_3166-2": "ISO 3166-2:NP",
        "region": "Asia",
        "sub-region": "Southern Asia",
        "intermediate-region": "",
        "region-code": "142",
        "sub-region-code": "034",
        "intermediate-region-code": ""
    },
    {
        "name": "Netherlands",
        "alpha-2": "NL",
        "alpha-3": "NLD",
        "country-code": "528",
        "iso_3166-2": "ISO 3166-2:NL",
        "region": "Europe",
        "sub-region": "Western Europe",
        "intermediate-region": "",
        "region-code": "150",
        "sub-region-code": "155",
        "intermediate-region-code": ""
    },
    {
        "name": "New Zealand",
        "alpha-2": "NZ",
        "alpha-3": "NZL",
        "country-code": "554",
        "iso_3166-2": "ISO 3166-2:NZ",
        "region": "Oceania",
        "sub-region": "Australia and New Zealand",
        "intermediate-region": "",
        "region-code": "009",
        "sub-region-code": "053",
        "intermediate-region-code": ""
    },
    {
        "name": "Nigeria",
        "alpha-2": "NG",
        "alpha-3": "NGA",
        "country-code": "566",
        "iso_3166-2": "ISO 3166-2:NG",
        "region": "Africa",
        "sub-region": "Sub-Saharan Africa",
        "intermediate-region": "Western Africa",
        "region-code": "002",
        "sub-region-code": "202",
        "intermediate-region-code": "011"
    },
    {
        "name": "Norway",
        "alpha-2": "NO",
        "alpha-3": "NOR",
        "country-code": "578",
        "iso_3166-2": "ISO 3166-2:NO",
        "region": "Europe",
        "sub-region": "Northern Europe",
        "intermediate-region": "",
        "region-code": "150",
        "sub-region-code": "154",
        "intermediate-region-code": ""
    },
    {
        "name": "Oman",
        "alpha-2": "OM",
        "alpha-3": "OMN",
        "country-code": "512",
        "iso_3166-2": "ISO 3166-2:OM",
        "region": "Asia",
        "sub-region": "Western Asia",
        "intermediate-region": "",
        "region-code": "142",
        "sub-region-code": "145",
        "intermediate-region-code": ""
    },
    {
        "name": "Pakistan",
        "alpha-2": "PK",
        "alpha-3": "PAK",
        "country-code": "586",
        "iso_3166-2": "ISO 3166-2:PK",
        "region": "Asia",
        "sub-region": "Southern Asia",
        "intermediate-region": "",
        "region-code": "142",
        "sub-region-code": "034",
        "intermediate-region-code": ""
    },
    {
        "name": "Panama",
        "alpha-2": "PA",
        "alpha-3": "PAN",
        "country-code": "591",
        "iso_3166-2": "ISO 3166-2:PA",
        "region": "Americas",
        "sub-region": "Latin America and the Caribbean",
        "intermediate-region": "Central America",
        "region-code": "019",
        "sub-region-code": "419",
        "intermediate-region-code": "013"
    },
    {
        "name": "Papua New Guinea",
        "alpha-2": "PG",
        "alpha-3": "PNG",
        "country-code": "598",
        "iso_3166-2": "ISO 3166-2:PG",
        "region": "Oceania",
        "sub-region": "Melanesia",
        "intermediate-region": "",
        "region-code": "009",
        "sub-region-code": "054",
        "intermediate-region-code": ""
    },
    {
        "name": "Paraguay",
        "alpha-2": "PY",
        "alpha-3": "PRY",
        "country-code": "600",
        "iso_3166-2": "ISO 3166-2:PY",
        "region": "Americas",
        "sub-region": "Latin America and the Caribbean",
        "intermediate-region": "South America",
        "region-code": "019",
        "sub-region-code": "419",
        "intermediate-region-code": "005"
    },
    {
        "name": "Peru",
        "alpha-2": "PE",
        "alpha-3": "PER",
        "country-code": "604",
        "iso_3166-2": "ISO 3166-2:PE",
        "region": "Americas",
        "sub-region": "Latin America and the Caribbean",
        "intermediate-region": "South America",
        "region-code": "019",
        "sub-region-code": "419",
        "intermediate-region-code": "005"
    },
    {
        "name": "Philippines",
        "alpha-2": "PH",
        "alpha-3": "PHL",
        "country-code": "608",
        "iso_3166-2": "ISO 3166-2:PH",
        "region": "Asia",
        "sub-region": "South-eastern Asia",
        "intermediate-region": "",
        "region-code": "142",
        "sub-region-code": "035",
        "intermediate-region-code": ""
    },
    {
        "name": "Poland",
        "alpha-2": "PL",
        "alpha-3": "POL",
        "country-code": "616",
        "iso_3166-2": "ISO 3166-2:PL",
        "region": "Europe",
        "sub-region": "Eastern Europe",
        "intermediate-region": "",
        "region-code": "150",
        "sub-region-code": "151",
        "intermediate-region-code": ""
    },
    {
        "name": "Portugal",
        "alpha-2": "PT",
        "alpha-3": "PRT",
        "country-code": "620",
        "iso_3166-2": "ISO 3166-2:PT",
        "region": "Europe",
        "sub-region": "Southern Europe",
        "intermediate-region": "",
        "region-code": "150",
        "sub-region-code": "039",
        "intermediate-region-code": ""
    },
    {
        "name": "Puerto Rico",
        "alpha-2": "PR",
        "alpha-3": "PRI",
        "country-code": "630",
        "iso_3166-2": "ISO 3166-2:PR",
        "region": "Americas",
        "sub-region": "Latin America and the Caribbean",
        "intermediate-region": "Caribbean",
        "region-code": "019",
        "sub-region-code": "419",
        "intermediate-region-code": "029"
    },
    {
        "name": "Qatar",
        "alpha-2": "QA",
        "alpha-3": "QAT",
        "country-code": "634",
        "iso_3166-2": "ISO 3166-2:QA",
        "region": "Asia",
        "sub-region": "Western Asia",
        "intermediate-region": "",
        "region-code": "142",
        "sub-region-code": "145",
        "intermediate-region-code": ""
    },
    {
        "name": "Romania",
        "alpha-2": "RO",
        "alpha-3": "ROU",
        "country-code": "642",
        "iso_3166-2": "ISO 3166-2:RO",
        "region": "Europe",
        "sub-region": "Eastern Europe",
        "intermediate-region": "",
        "region-code": "150",
        "sub-region-code": "151",
        "intermediate-region-code": ""
    },
    {
        "name": "Saudi Arabia",
        "alpha-2": "SA",
        "alpha-3": "SAU",
        "country-code": "682",
        "iso_3166-2": "ISO 3166-2:SA",
        "region": "Asia",
        "sub-region": "Western Asia",
        "intermediate-region": "",
        "region-code": "142",
        "sub-region-code": "145",
        "intermediate-region-code": ""
    },
    {
        "name": "Singapore",
        "alpha-2": "SG",
        "alpha-3": "SGP",
        "country-code": "702",
        "iso_3166-2": "ISO 3166-2:SG",
        "region": "Asia",
        "sub-region": "South-eastern Asia",
        "intermediate-region": "",
        "region-code": "142",
        "sub-region-code": "035",
        "intermediate-region-code": ""
    },
    {
        "name": "Slovakia",
        "alpha-2": "SK",
        "alpha-3": "SVK",
        "country-code": "703",
        "iso_3166-2": "ISO 3166-2:SK",
        "region": "Europe",
        "sub-region": "Eastern Europe",
        "intermediate-region": "",
        "region-code": "150",
        "sub-region-code": "151",
        "intermediate-region-code": ""
    },
    {
        "name": "Slovenia",
        "alpha-2": "SI",
        "alpha-3": "SVN",
        "country-code": "705",
        "iso_3166-2": "ISO 3166-2:SI",
        "region": "Europe",
        "sub-region": "Southern Europe",
        "intermediate-region": "",
        "region-code": "150",
        "sub-region-code": "039",
        "intermediate-region-code": ""
    },
    {
        "name": "Spain",
        "alpha-2": "ES",
        "alpha-3": "ESP",
        "country-code": "724",
        "iso_3166-2": "ISO 3166-2:ES",
        "region": "Europe",
        "sub-region": "Southern Europe",
        "intermediate-region": "",
        "region-code": "150",
        "sub-region-code": "039",
        "intermediate-region-code": ""
    },
    {
        "name": "Sweden",
        "alpha-2": "SE",
        "alpha-3": "SWE",
        "country-code": "752",
        "iso_3166-2": "ISO 3166-2:SE",
        "region": "Europe",
        "sub-region": "Northern Europe",
        "intermediate-region": "",
        "region-code": "150",
        "sub-region-code": "154",
        "intermediate-region-code": ""
    },
    {
        "name": "Switzerland",
        "alpha-2": "CH",
        "alpha-3": "CHE",
        "country-code": "756",
        "iso_3166-2": "ISO 3166-2:CH",
        "region": "Europe",
        "sub-region": "Western Europe",
        "intermediate-region": "",
        "region-code": "150",
        "sub-region-code": "155",
        "intermediate-region-code": ""
    },
    {
        "name": "Taiwan, Province of China",
        "alpha-2": "TW",
        "alpha-3": "TWN",
        "country-code": "158",
        "iso_3166-2": "ISO 3166-2:TW",
        "region": "Asia",
        "sub-region": "Eastern Asia",
        "intermediate-region": "",
        "region-code": "142",
        "sub-region-code": "030",
        "intermediate-region-code": ""
    },
    {
        "name": "Thailand",
        "alpha-2": "TH",
        "alpha-3": "THA",
        "country-code": "764",
        "iso_3166-2": "ISO 3166-2:TH",
        "region": "Asia",
        "sub-region": "South-eastern Asia",
        "intermediate-region": "",
        "region-code": "142",
        "sub-region-code": "035",
        "intermediate-region-code": ""
    },
    {
        "name": "Trinidad and Tobago",
        "alpha-2": "TT",
        "alpha-3": "TTO",
        "country-code": "780",
        "iso_3166-2": "ISO 3166-2:TT",
        "region": "Americas",
        "sub-region": "Latin America and the Caribbean",
        "intermediate-region": "Caribbean",
        "region-code": "019",
        "sub-region-code": "419",
        "intermediate-region-code": "029"
    },
    {
        "name": "Tunisia",
        "alpha-2": "TN",
        "alpha-3": "TUN",
        "country-code": "788",
        "iso_3166-2": "ISO 3166-2:TN",
        "region": "Africa",
        "sub-region": "Northern Africa",
        "intermediate-region": "",
        "region-code": "002",
        "sub-region-code": "015",
        "intermediate-region-code": ""
    },
    {
        "name": "Turkey",
        "alpha-2": "TR",
        "alpha-3": "TUR",
        "country-code": "792",
        "iso_3166-2": "ISO 3166-2:TR",
        "region": "Asia",
        "sub-region": "Western Asia",
        "intermediate-region": "",
        "region-code": "142",
        "sub-region-code": "145",
        "intermediate-region-code": ""
    },
    {
        "name": "Uganda",
        "alpha-2": "UG",
        "alpha-3": "UGA",
        "country-code": "800",
        "iso_3166-2": "ISO 3166-2:UG",
        "region": "Africa",
        "sub-region": "Sub-Saharan Africa",
        "intermediate-region": "Eastern Africa",
        "region-code": "002",
        "sub-region-code": "202",
        "intermediate-region-code": "014"
    },
    {
        "name": "United Kingdom of Great Britain and Northern Ireland",
        "alpha-2": "GB",
        "alpha-3": "GBR",
        "country-code": "826",
        "iso_3166-2": "ISO 3166-2:GB",
        "region": "Europe",
        "sub-region": "Northern Europe",
        "intermediate-region": "",
        "region-code": "150",
        "sub-region-code": "154",
        "intermediate-region-code": ""
    },
    {
        "name": "United States Minor Outlying Islands",
        "alpha-2": "UM",
        "alpha-3": "UMI",
        "country-code": "581",
        "iso_3166-2": "ISO 3166-2:UM",
        "region": "Oceania",
        "sub-region": "Micronesia",
        "intermediate-region": "",
        "region-code": "009",
        "sub-region-code": "057",
        "intermediate-region-code": ""
    },
    {
        "name": "Uruguay",
        "alpha-2": "UY",
        "alpha-3": "URY",
        "country-code": "858",
        "iso_3166-2": "ISO 3166-2:UY",
        "region": "Americas",
        "sub-region": "Latin America and the Caribbean",
        "intermediate-region": "South America",
        "region-code": "019",
        "sub-region-code": "419",
        "intermediate-region-code": "005"
    },
    {
        "name": "Vanuatu",
        "alpha-2": "VU",
        "alpha-3": "VUT",
        "country-code": "548",
        "iso_3166-2": "ISO 3166-2:VU",
        "region": "Oceania",
        "sub-region": "Melanesia",
        "intermediate-region": "",
        "region-code": "009",
        "sub-region-code": "054",
        "intermediate-region-code": ""
    },
    {
        "name": "Zimbabwe",
        "alpha-2": "ZW",
        "alpha-3": "ZWE",
        "country-code": "716",
        "iso_3166-2": "ISO 3166-2:ZW",
        "region": "Africa",
        "sub-region": "Sub-Saharan Africa",
        "intermediate-region": "Eastern Africa",
        "region-code": "002",
        "sub-region-code": "202",
        "intermediate-region-code": "014"
    }
]